# Generated by Django 5.2 on 2025-04-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_details_product_detail_product_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
